export enum ROUTERS {
  HOME = "/",
  USER = "/user",
  USER_CURRENT = "/user/current",
  STUDIO = "/studio",
  STUDIO_VIDEOS = "/studio/videos",
  VIDEOS = "/videos",
  SEARCH = "/search",
  FEED_TRENDING = "/feed/trending",
  FEED_SUBSCRIBED = "/feed/subscribed",
  PLAYLIST = "/playlist",
  PLAYLIST_LIKED = "/playlist/liked",
  PLAYLIST_HISTORY = "/playlist/history",
  PROTECTED = "/protected",
}