export enum ROUTERS {
  HOME = "/",
  USER = "/user",
  USER_CURRENT = "/user/current",
  STUDIO = "/studio",
  STUDIO_VIDEOS = "/studio/videos",
  VIDEOS = "/videos",
  SEARCH = "/search",
  FEED_TRENDING = "/feed/trending",
  FEED_SUBSCRIBED = "/feed/subscribed",
  PLAYLISTS = "/playlists",
  PLAYLISTS_LIKED = "/playlists/liked",
  PLAYLISTS_HISTORY = "/playlists/history",
  PROTECTED = "/protected",
}